cmake: use C++17 instead of 14
Recent ICU headers don't work with C++14, e.g.

```
In file included from [...]/src/msix/PAL/Applicability/Linux/Applicability.cpp:6:
In file included from /usr/include/unicode/uloc.h:27:
In file included from /usr/include/unicode/uenum.h:25:
/usr/include/unicode/localpointer.h:559:26: error: 'auto' not allowed in template parameter until C++17
  559 | template <typename Type, auto closeFunction>
      |                          ^~~~
```
and
```
In file included from [...]/lib/xerces/src/xercesc/util/regx/RangeToken.cpp:40:
In file included from /usr/include/unicode/uset.h:37:
/usr/include/unicode/char16ptr.h:317:10: error: no member named 'is_convertible_v' in namespace 'std'
  317 |     std::is_convertible_v<T, std::u16string_view>
      |     ~~~~~^
```